### ISSUE TITLE
4.0 and 4.0.1 update increased load times by 10+ seconds

### ISSUE THREAD

**Issue by Endda** [brainstormforce/astra#4927] opened 2023-01-13 22:03 UTC
### Describe the bug:
I should be able to view my woocommerce products without waiting 12 seconds for the page to load

### To reproduce:
update astra to 4.0/4.0.1 and then view woocommerce products

I updated Astra to 4.0 this week and was met with some nasty bugs and a massive increase in load times. This is so unacceptable and has caused incredible frustration from a theme that I have had such a great experience from.

I already have a support ticket open about the header issues caused by 4.0, which was thankfully addressed when 4.0.1 was released, but now I'm facing increased loading times of 10 additional seconds JUST from updating Astra Pro (plugin) and the Astra theme to the latest version.

without cache, my woocommerce products usually load in about 2.5 seconds (as shown by query monitor), but when I update them to the latest version (4.0 and 4.0.1), these load times jump to 12+ seconds.

I'm so pissed off about this that I could spit fire (as my mother used to say).

please look into this issue. I'm forced to downgrade because waiting 10+ seconds for pages to load (that aren't cached) is just unacceptable

I have to keep the website downgraded so my visitors can actually experience the website without giving up. I tried disabling plugins to make the load times better. but the only thing that made load times go from 12 seconds back to 2.5 seconds was downgrading to the older version of Astra (3.9.4)

### Expected behavior:
pages should load in 2.5 seconds like they did with version  3.9.4

### Screenshots:
query monitor shows 12+ seconds to load a page with astra 4.0.1

### Isolating the problem:

- [X] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

### Astra Theme version:
4.0 & 4.0.1

**Comment by thebengalboy** [comment] 2023-01-25 11:09
This has been addressed and released with the version Astra theme 4.0.2 and Addon 4.0.1. For the time being, we're closing the issue, but if you notice anything new, please let us know.

**Closed by thebengalboy** 2023-01-25 11:09 UTC
Labels: bug

**Comment by thebengalboy** [comment] 2023-01-25 14:24
@Endda Please [open a support ticket](https://wpastra.com/support/open-a-ticket/) with the details of your site environment. Our support team will troubleshoot and determine the root cause of the problem. Thanks

**Comment by Endda** [comment] 2023-01-25 14:29
@thebengalboy I have, and I keep getting the runaround. I opened that ticket up weeks ago when this 4.0 update was first released :( only for it to get closed without any help

what has happened with the team behind this theme. updates used to be flawless and support used to be top-notch.
things have gone so downhill this last year or so. . .

**Comment by Endda** [comment] 2023-01-25 14:36
https://store.brainstormforce.com/support/my-tickets/?conversation_id=2124620417 is the latest ticket. I told them the URL for the staging site and was replied with "Thank you for writing back to us. I sincerely apologize for the delay in response, since we are having a high volume of tickets as of late." and then ticket was closed 3 days later without any additional response

**Comment by thebengalboy** [comment] 2023-01-26 03:23
Hi @Endda 

We apologize for the inconvenience you have experienced. Could you please reply to the old ticket or create a new one, so we can assist you in resolving the issue you are having with the 4.0 update? We value your feedback and will do our best to improve our support and update process.

Thank you for your understanding and let me know the ticket ID once you reply to the ticket.

**Comment by Endda** [comment] 2023-01-26 03:29
> Hi @Endda
> 
> We apologize for the inconvenience you have experienced. Could you please reply to the old ticket or create a new one, so we can assist you in resolving the issue you are having with the 4.0 update? We value your feedback and will do our best to improve our support and update process.
> 
> Thank you for your understanding and let me know the ticket ID once you reply to the ticket.

I already linked the first ticket in this thread. And I submitted a new ticket today about the same issue and was told the team was aware of the issue but is working on a solution

So I replied asking why they closed this bug report when the issue was acknowledged and was still being worked on

I honestly don't know who you have running support at this company anymore but it's been atrocious lately (it used to be top notch)
