### ISSUE TITLE
3.7.4 adds unwanted CSS to front end

### ISSUE THREAD

**Issue by ElectricFeet** [brainstormforce/astra#3639] opened 2021-10-30 12:45 UTC
### Describe the bug:
3.7.4 adds unwanted CSS to front end. See screenshots below.

The following rule has been added to the stylesheet (by class-astra-dynamic-css.php, line 2246:

`.entry-content > .wp-block-group, 
.entry-content > .wp-block-media-text, 
.entry-content > .wp-block-cover, 
.entry-content > .wp-block-columns {
	max-width: 58em;
	width: calc(100% - 4em);
	margin-left: auto;
	margin-right: auto;
}`

Obviously, this reduces the width of the standard WP elements.

Anyone who is using UAG advanced columns will not be affected by the change. However, anyone using standard WP-columns is affected in a big way. I suspect that this was a rule intended for the back end that has contaminated the front end, or a rule intended for tablets/phones that has been left above the desktop breakpoint.

### To reproduce:
1. Installed Astra 3.7.4.
2. Added `add_filter( 'astra_get_option_improve-gb-editor-ui', '__return_true' );` to functions.php, as suggested in https://wpastra.com/docs/gutenberg-ui-improvements-with-astra/

### Expected behavior:
No change to WP columns on the front end site

### Screenshots:
An example on the frontend looks like this:

![Frontend WP-cols vs UAG cols](https://user-images.githubusercontent.com/6003638/139493875-43830acf-958b-4cdb-9b84-8d424e34407b.jpg)

where you can see that there are width reductions. The backend (editor) looks like this: 

![Backend WP-cols vs UAG cols](https://user-images.githubusercontent.com/6003638/139493909-9cd0df41-71b5-4034-b97b-c152ae4d4d90.jpg)

### Isolating the problem:

- [ Yes] This bug happens with no other plugins activated
- [ No ] This bug happens with a default WordPress theme active _(No, obviously, as this is an issue with the Astra theme)_
- [Yes ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

### Astra Theme version:
3.7.4

### Additional info:
I added the `add_filter` code to the functions.php on a site that is yet to be published, with the logic that I wanted the new site to be as "standard" Astra as possible moving forward. Obviously, I can avoid this bug by removing that line. However, the CSS above doesn't seem to me to be intended, hence my reporting it as a bug and not seeing it as a feature.

**Comment by NicoHood** [comment] 2021-12-26 15:23
What about this issue? You introduced new layouts and did not manage to fix them within multiple month!

**Comment by imnavanath** [comment] 2021-12-30 07:43
Hi @ElectricFeet,

Thank you for reaching out to us.

We replicated the case on our end as suggested markup from @NicoHood, and as per your screenshot @ElectricFeet,

The layout change is because of the new improvement in that update. The scenario was like this - 

**Default Layout:** The default layout should work as a boxed layout.
**Wide Layout:** Wide-format will take the site container's width from your setup.
**Full-width Layout:** Full-width layout will go edge-to-edge of the screen.

We tried to achieve this result -
Editor - https://share.bsf.io/6quEkROQ
Frontend - https://share.bsf.io/jkumq7gm
You can see the visual representation of this here - https://share.bsf.io/d5uNY8lL

We implemented this as per the design aspect to make users' layouts convenient and adjustable for their sites.

And as the unset block layouts are "Default" ones, the width dimensions are updated over here. But if you can make the layouts as Wide/Full-width (per requirement), then the boxed width issue will resolve.

Here is the small demonstration from my setup - https://share.bsf.io/Apuxn6pr

I hope that helps you. Let us know your feedback as well.

Thanks & Regards!

cc: @NicoHood

**Comment by NicoHood** [comment] 2022-01-06 13:47
I also want to note, that whole layouts broke with this change. But even worse, you cannot fix them. I took the "mountains" starter site from astra templates library.

## Before

Editor:
![grafik](https://user-images.githubusercontent.com/6888294/148391198-7ee2fb15-9c80-49cd-8671-5364bbce9130.png)

Final site:
![grafik](https://user-images.githubusercontent.com/6888294/148391250-9a3ae91a-219e-4b37-a4ae-db10e747928e.png)

## After

Editor:
![grafik](https://user-images.githubusercontent.com/6888294/148391317-4be7b22c-2e2b-4d80-89d7-4b63a285f170.png)

Final site:
![grafik](https://user-images.githubusercontent.com/6888294/148391337-881ab266-08ac-4f1d-adf9-bfe605260896.png)

There is **no way to enlarge the 3 image columns**. They are just always so small, not chance to fix this behavior. However I this might be an even different issue than originally reported, as this also affects the final webpage, not only the editor.

@imnavanath can you please take a closer look at those upgrades pages?

**Comment by NicoHood** [comment] 2022-01-06 13:47
I just noticed, that the width settings button is missing for the columns:
![grafik](https://user-images.githubusercontent.com/6888294/148391915-4585c026-10cc-4050-b431-02c584f63177.png)

This is your video:
![grafik](https://user-images.githubusercontent.com/6888294/148392098-b868b6ff-4318-4919-ab4d-aa9fa8764429.png)

Looking at [your video](https://share.bsf.io/Apuxn6pr) there is one at your place. Maybe the `astra_get_option_improve-gb-editor-ui` filter is missing to enable this option?

**Comment by imnavanath** [comment] 2022-01-17 08:13
Hi @NicoHood,

I've checked the same case with the [Mountain starter template](https://websitedemos.net/mountain-08/) on my end. I came across the layout-changing scenario that you were trying to say. 

See here the screencast from my end - https://share.bsf.io/RBuy9NBR

**PS:** Firstly, set the filter as 'false' (i.e., considered as old setup), then I switched it to new layout (by setting it as 'true') 
When switching to a new UI layout, it shrunk as you were also faced. It happened because the default layout was active & as per new design compatibility (just discussed previously) it looks like box view. But as soon as I changed the column layout to 'wide width.' It fixes as per the wide container size. Likewise, it can handle.

**Answering the next query:** The column block doesn't have a 'wide' layout option.
**->** The case might be your parent Astra theme is active. On my end child theme is activated (which doesn't have a theme.json file). If any theme has theme.json file, then the column block does not show a wide layout option. 

You can check this by adding [Astra child theme](https://wpastra.com/child-theme-generator) with adding filter as we are discussing - 
```
add_filter( 'astra_get_option_improve-gb-editor-ui', '__return_true' );
```


I hope that answers your queries. Please let us know if there is anything.

Thanks & Regards!
cc: @ElectricFeet

**Comment by NicoHood** [comment] 2022-01-17 08:46
At around 1:25 in your screencast you change back to "Wide Layout", My issue is, that **I do not have this button available**. See:

![image](https://user-images.githubusercontent.com/6888294/149735855-71b5b417-0069-43e4-9902-058a5dab0c46.png)

In order for you to reproduce this with a minimal test site, you can use my login I provided you with **credentials of my test site in the Astra Pro Support Ticket**.

**Comment by imnavanath** [comment] 2022-01-17 09:48
Correct @NicoHood that's right. Same thing I said,

-> The case is, might be your parent (MAIN) Astra theme is active. On my end child theme is activated (which doesn't have a theme.json file). If any theme has theme.json file, then the column block does not show a wide layout option.

As the main Astra theme has theme.json file that's why the 'wide' option is not visible but if we switch to child theme by default it don't have any theme.json file that's why there appearing 'wide' layout option correctly.

You can check this by adding [Astra child theme](https://wpastra.com/child-theme-generator).

Best Regards.

**Comment by NicoHood** [comment] 2022-01-17 09:51
But why do I need a child theme? Why would I want to do that? I want this feature in my pura astra theme. What is the reason for not enabling this in the main theme?

**Comment by NicoHood** [comment] 2022-01-31 09:02
The Astra Pro Supported mentioned those two upstream issues, that I want to share with you guys.
https://github.com/WordPress/gutenberg/issues/33374
https://github.com/WordPress/gutenberg/issues/37036

I still dont really get why this happens or how I could avoid that with the pure astra theme.

**Comment by NicoHood** [comment] 2022-02-17 07:04
Would you mind looking at the comment in the upstream issue, if the workaround is suitable for astra theme?
https://github.com/WordPress/gutenberg/issues/33374#issuecomment-1042310425

**Comment by NicoHood** [comment] 2022-02-22 11:34
Hey @imnavanath thanks for taking the time! This works for me, if I have a **columns inside a group**. It does not work, if I have a **group inside a cover**. That should be fixed as well.

I also would love to have a single snippet, that I can add via code snippets plugin. However I am not that deep into the wordpress code, that I could make it work properly. Here is my attempt, **but it does not work!**

```php
// https://gist.github.com/Luehrsen/c4aad3b33435058c19ea80f5f1c268e8
add_action( 'admin_footer', function () { ?>
<script>
/**
 * @type {string[]} Array of block names that should be excluded from the layout settings.
 */
const haystack = ['core/group'];

wp.hooks.addFilter(
	'blocks.registerBlockType',
	'lh/fseFixes/layoutSettings',
	(settings, name) => {
		if (!haystack.includes(name)) {
			return settings;
		}

		const newSettings = {
			...settings,
			supports: {
				...(settings.supports || {}),
				layout: {
					...(settings.supports.layout || {}),
					allowEditing: false,
					allowSwitching: false,
					allowInheriting: true,
				},
				__experimentalLayout: {
					...(settings.supports.__experimentalLayout || {}),
					allowEditing: false,
					allowSwitching: false,
					allowInheriting: true,
				},
			},
		};
		return newSettings;
	},
	20
);

wp.hooks.addFilter(
	'blocks.getBlockAttributes',
	'lh/fseFixes',
	(attributes, blockType) => {
		if (!haystack.includes(blockType.name)) {
			return attributes;
		}

		attributes = {
			...attributes,
			layout: {
				inherit: true,
			},
		};

		return attributes;
	}
);
</script>
<?php } );
```

**Comment by NicoHood** [comment] 2022-03-29 21:25
The wordpress upstream developer mentioned, that this issue must be fixed in the theme itself. More details here:
https://github.com/WordPress/gutenberg/issues/33374#issuecomment-1080803267

I unfortunately do not know more about this, as I do not develop wordpress themes. You should be able to work with this information.

**Comment by NicoHood** [comment] 2022-06-29 17:37
But the wordpress devs stated, that this should be changed by theme developers. I am kinda lost, as nobody seem to want to fix this. For me, I am fine with either a wordpress core or astra fix. However you as a developer can possibly argument better on that and show the demand to the wordpress core developers.

Astra is THE most popular theme. If you speak a word there with the ASTRA name, it has more weight than me writing over and over.

In either way: If you can help to fix this, I'd be super happy! Thanks :)

**Comment by thebengalboy** [comment] 2023-01-25 11:43
Hi @NicoHood 

I see the above PR is merged with WordPress core. Does it solve the problem? Unfortunately, we can not handle this from the theme.

_[This specific GitHub issue is very old. If you believe Astra has to bring something on this, please open a new one]_

**Closed by thebengalboy** 2023-01-25 11:43 UTC
Labels: bug
