### ISSUE TITLE
Header Builder - PHP Notice:  Function the_widget was called <strong>incorrectly</strong>.

### ISSUE THREAD

**Issue by WildeWebMarketing** [brainstormforce/astra#4735] opened 2022-11-07 20:03 UTC
When adding widget to Header Builder, debug log throws error upon each page load,

`[07-Nov-2022 19:58:31 UTC] PHP Notice:  Function the_widget was called <strong>incorrectly</strong>. Widgets need to be registered using <code>register_widget()</code>, before they can be displayed. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.9.0.) in /home/wildeweb/wp-includes/functions.php on line 5835`

**Comment by thebengalboy** [comment] 2022-11-08 05:29
Hello @WildeWebMarketing 

We tried with a fresh install by adding widgets to the Header area and following the debug log, but it's not exactly the same as what you're experiencing. I'm not sure, but it could be a site-specific problem caused by the environment or something else.

Could you please contact our support center by submitting a [support ticket here](https://wpastra.com/support/open-a-ticket/)? Our support team will assist you in this matter.

Thanks

**Comment by thebengalboy** [comment] 2022-12-19 13:40
Hello @WildeWebMarketing 

I'm curious to know if you have the problem resolved. Since it's site-specific, I'm closing it.

Thanks

**Closed by thebengalboy** 2022-12-19 13:40 UTC
Labels: bug
